# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 \
    --display_data=true
    # <- Optional: specify video codec (auto, h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm" \
  --dataset.streaming_encoding=true \
  # --dataset.vcodec=auto \
  --dataset.encoder_threads=2
```
"""

import logging
import sys
import time
from contextlib import suppress
from dataclasses import asdict, dataclass, field
from functools import partial
from pathlib import Path
from pprint import pformat
from typing import Any, Protocol

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
    make_processors_for_teleop_robot_pair,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
    aubo_i10  
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    get_safe_torch_device,
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data
from datetime import datetime
import os


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path').
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 100
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1', 'auto',
    # or hardware-specific: 'h264_videotoolbox', 'h264_nvenc', 'h264_vaapi', 'h264_qsv'.
    # Use 'auto' to auto-detect the best available hardware encoder.
    vcodec: str = "libsvtav1"
    # Enable streaming video encoding: encode frames in real-time during capture instead
    # of writing PNG images first. Makes save_episode() near-instant. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding
    streaming_encoding: bool = False
    # Maximum number of frames to buffer per camera when using streaming encoding.
    # ~1s buffer at 30fps. Provides backpressure if the encoder can't keep up.
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder instance. None = auto (codec default).
    # Lower values reduce CPU usage, maps to 'lp' (via svtav1-params) for libsvtav1 and 'threads' for h264/hevc..
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


class RecordLoopObserver(Protocol):
    """Optional hook surface for record_loop's per-cycle send/capture lifecycle.

    Implementations must be generic: record_loop never imports C0-specific
    modules and never hardcodes robot types, DO pins, or trace field names.
    methods receives the plain record_loop data (robot, dataset, the
    dataset-bound action values, the action actually handed to the robot, the
    action returned by ``send_action``, and the candidate frame index derived
    from the dataset episode buffer), so an exception raised by any method
    identifies its stage by construction.
    Methods are only invoked while ``dataset is not None``; when the observer
    is None, record_loop keeps its original behavior exactly.
    """

    def before_send(
        self,
        *,
        robot: Robot,
        dataset: LeRobotDataset,
        action: RobotAction,
        robot_action_to_send: RobotAction,
        candidate_frame_index: int,
    ) -> None: ...

    def on_send_success(
        self,
        *,
        robot: Robot,
        dataset: LeRobotDataset,
        action: RobotAction,
        robot_action_to_send: RobotAction,
        sent_action: RobotAction,
        candidate_frame_index: int,
    ) -> None: ...

    def on_send_failure(
        self,
        *,
        robot: Robot,
        dataset: LeRobotDataset,
        action: RobotAction,
        robot_action_to_send: RobotAction,
        candidate_frame_index: int,
        error: Exception,
    ) -> None: ...

    def on_add_frame_success(
        self,
        *,
        robot: Robot,
        dataset: LeRobotDataset,
        action: RobotAction,
        robot_action_to_send: RobotAction,
        candidate_frame_index: int,
    ) -> None: ...

    def on_add_frame_failure(
        self,
        *,
        robot: Robot,
        dataset: LeRobotDataset,
        action: RobotAction,
        robot_action_to_send: RobotAction,
        candidate_frame_index: int,
        error: Exception,
    ) -> None: ...


class RecordEpisodeLifecycleObserver(Protocol):
    """Optional per-episode/session lifecycle hook surface for the record loop.

    Implementations must be generic: ``lerobot_record`` never imports C0-specific
    modules and never hardcodes robot types, DO pins, or gripper semantics. The
    lifecycle observer orchestrates, per episode attempt: which frame observer
    ``record_loop`` uses, how a completed episode buffer is saved, and what
    happens on rerecord/stop/incomplete. It also receives the dataset
    finalize outcome so post-save promotion can run only after the writer was
    safely closed through the dataset's public lifecycle.

    When the observer is None, the record loop keeps its original behavior
    exactly: one direct ``dataset.save_episode()`` per non-rerecorded episode
    (including an episode stopped mid-way), unchanged rerecord handling, reset
    loops without a dataset, and a plain ``dataset.finalize()``.

    Exception contract (deterministic and tested):
    - Observer exceptions propagate whenever no other exception is in flight.
    - When the episode's ``record_loop`` already raised, the incomplete
      notification is best-effort: its exception is logged as context and the
      original record exception keeps propagating.
    - On finalize failure the failure notification runs while the finalize
      exception is propagating: its exception is logged and never masks the
      finalize error, which keeps propagating.
    - On finalize success the success notification may raise (it is the only
      error in flight); while another exception is already propagating its
      exception is only logged.
    """

    def episode_frame_observer(self) -> RecordLoopObserver | None:
        """Return the frame observer for the episode attempt about to start.

        Called once per episode attempt, before ``record_loop`` begins and
        again for every rerecord attempt. Implementations must fail closed
        here when the episode must not start at all (for example a manifest
        count/index mismatch): raising prevents any send/save for it.
        Returning None records the episode without a frame observer.
        """
        ...

    def on_episode_rerecord(
        self, *, robot: Robot, dataset: LeRobotDataset, episode_index: int
    ) -> None:
        """The current episode attempt is discarded and will be re-recorded.

        Called after the episode's record and reset loops, right before
        ``dataset.clear_episode_buffer()``, and never for an episode that was
        saved. The episode index stays at ``episode_index`` for the next
        attempt.
        """
        ...

    def on_episode_incomplete(
        self, *, robot: Robot, dataset: LeRobotDataset, episode_index: int, reason: str
    ) -> None:
        """The current episode attempt ends unsaved (operator stop or failure).

        Called for an operator stop before save, or best-effort when the
        episode's ``record_loop`` or reset phase raised (in which case observer
        exceptions are logged and never mask the original error). The unsaved
        buffer must not be treated as a completed episode.
        """
        ...

    def save_episode(self, *, robot: Robot, dataset: LeRobotDataset, episode_index: int) -> None:
        """Orchestrate the save of one completed, non-rerecorded episode.

        Must perform the episode's single logical save. Called exactly once
        per completed episode; rerecorded attempts and stopped episodes never
        reach this hook. Exceptions propagate and must not be retried here.
        """
        ...

    def on_dataset_finalize_success(
        self, *, dataset: LeRobotDataset, recorded_episode_count: int
    ) -> None:
        """The dataset finalized/closed its writer through its public lifecycle.

        Every previously saved episode is durably finalized at this point; this
        is the only place where post-save promotion may run. May raise when a
        promotion fails: no episode save may be retried from here.
        """
        ...

    def on_dataset_finalize_failure(self, *, dataset: LeRobotDataset, error: BaseException) -> None:
        """The dataset finalize step raised; the original exception keeps propagating.

        Implementations must keep every previously saved episode pending and
        must not fabricate finalized evidence. This hook itself must not raise:
        its exceptions are logged, never masked, and never replace the
        finalize error.
        """
        ...


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    display_compressed_images: bool = False,
    observer: RecordLoopObserver | None = None,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    timestamp = 0
    start_episode_t = time.perf_counter()
    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        obs = robot.get_observation()

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Get action from either policy or teleop
        if policy is not None and preprocessor is not None and postprocessor is not None:
            action_values = predict_action(
                observation=observation_frame,
                policy=policy,
                device=get_safe_torch_device(policy.config.device),
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                use_amp=policy.config.use_amp,
                task=single_task,
                robot_type=robot.robot_type,
            )

            act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
        else:
            logging.info(
                "No policy or teleoperator provided, skipping action generation."
                "This is likely to happen when resetting the environment without a teleop device."
                "The robot won't be at its rest position at the start of the next episode."
            )
            continue

        # Applies a pipeline to the action, default is IdentityProcessor
        if policy is not None and act_processed_policy is not None:
            action_values = act_processed_policy
            robot_action_to_send = robot_action_processor((act_processed_policy, obs))
        else:
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.

        # The optional observer only participates in the dataset capture
        # lifecycle (dataset is not None). The candidate frame index mirrors
        # add_frame's rule: the current episode_buffer size, or 0 when no
        # episode buffer exists yet.
        active_observer = observer if dataset is not None else None
        candidate_frame_index = 0
        if active_observer is not None:
            episode_buffer = getattr(dataset, "episode_buffer", None)
            if episode_buffer is not None:
                candidate_frame_index = episode_buffer["size"]
            active_observer.before_send(
                robot=robot,
                dataset=dataset,
                action=action_values,
                robot_action_to_send=robot_action_to_send,
                candidate_frame_index=candidate_frame_index,
            )

        try:
            _sent_action = robot.send_action(robot_action_to_send)
        except Exception as send_error:
            if active_observer is not None:
                active_observer.on_send_failure(
                    robot=robot,
                    dataset=dataset,
                    action=action_values,
                    robot_action_to_send=robot_action_to_send,
                    candidate_frame_index=candidate_frame_index,
                    error=send_error,
                )
            raise
        if active_observer is not None:
            active_observer.on_send_success(
                robot=robot,
                dataset=dataset,
                action=action_values,
                robot_action_to_send=robot_action_to_send,
                sent_action=_sent_action,
                candidate_frame_index=candidate_frame_index,
            )

        # Write to dataset
        if dataset is not None:
            action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            try:
                dataset.add_frame(frame)
            except Exception as add_frame_error:
                if active_observer is not None:
                    active_observer.on_add_frame_failure(
                        robot=robot,
                        dataset=dataset,
                        action=action_values,
                        robot_action_to_send=robot_action_to_send,
                        candidate_frame_index=candidate_frame_index,
                        error=add_frame_error,
                    )
                raise
            if active_observer is not None:
                active_observer.on_add_frame_success(
                    robot=robot,
                    dataset=dataset,
                    action=action_values,
                    robot_action_to_send=robot_action_to_send,
                    candidate_frame_index=candidate_frame_index,
                )

        if display_data:
            log_rerun_data(
                observation=obs_processed, action=action_values, compress_images=display_compressed_images
            )

        dt_s = time.perf_counter() - start_loop_t

        sleep_time_s: float = 1 / fps - dt_s
        if sleep_time_s < 0:
            logging.warning(
                f"Record loop is running slower ({1 / dt_s:.1f} Hz) than the target FPS ({fps} Hz). Dataset frames might be dropped and robot control might be unstable. Common causes are: 1) Camera FPS not keeping up 2) Policy inference taking too long 3) CPU starvation"
            )

        precise_sleep(max(sleep_time_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t


def _notify_lifecycle_observer(hook: str, call, *, original_error: BaseException | None) -> None:
    """Run one lifecycle observer hook with deterministic exception semantics.

    Without an in-flight original error the observer's exception propagates
    (it is the only error), including KeyboardInterrupt and SystemExit. With
    one, every observer BaseException is logged as checkable context and the
    original error keeps propagating unmasked. Logger failures never replace
    or reorder that original error.
    """

    try:
        call()
    except BaseException as observer_error:
        if original_error is None:
            raise
        bound_hook = hook
        bound_observer_error = observer_error
        bound_original_error = original_error
        with suppress(BaseException):
            logging.getLogger(__name__).error(
                "record episode lifecycle hook %s failed with %r; the original "
                "error %r keeps propagating",
                bound_hook,
                bound_observer_error,
                bound_original_error,
                exc_info=True,
            )


def record_episode_sessions(
    *,
    robot: Robot,
    teleop: Teleoperator | list[Teleoperator] | None,
    policy: PreTrainedPolicy | None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],
    dataset: LeRobotDataset,
    events: dict,
    fps: int,
    num_episodes: int,
    episode_time_s: int | float,
    reset_time_s: int | float,
    single_task: str,
    play_sounds: bool,
    display_data: bool,
    display_compressed_images: bool,
    lifecycle: RecordEpisodeLifecycleObserver | None = None,
) -> int:
    """Run the record/reset/rerecord/save episode loop (extracted from record()).

    Returns the number of episodes whose save returned. With ``lifecycle=None``
    the behavior is exactly the historical ``record()`` loop: one direct
    ``dataset.save_episode()`` per non-rerecorded episode (including an
    episode stopped mid-way), unchanged rerecord handling, reset loops without
    a dataset, and no observer of any kind. With a lifecycle observer, the
    frame observer comes from ``episode_frame_observer()`` per attempt, saves
    go exclusively through ``lifecycle.save_episode()``, rerecord/stop notify
    the observer, and a stopped episode is never saved.
    """

    recorded_episodes = 0
    while recorded_episodes < num_episodes and not events["stop_recording"]:
        log_say(f"Recording episode {dataset.num_episodes}", play_sounds)
        frame_observer = lifecycle.episode_frame_observer() if lifecycle is not None else None
        terminal = False
        phase = "record_loop"
        try:
            record_loop(
                robot=robot,
                events=events,
                fps=fps,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                teleop=teleop,
                policy=policy,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                dataset=dataset,
                control_time_s=episode_time_s,
                single_task=single_task,
                display_data=display_data,
                display_compressed_images=display_compressed_images,
                observer=frame_observer,
            )

            # Execute a few seconds without recording to give time to manually reset the environment
            # Skip reset for the last episode to be recorded
            if not events["stop_recording"] and (
                (recorded_episodes < num_episodes - 1) or events["rerecord_episode"]
            ):
                log_say("Reset the environment", play_sounds)

                # reset g1 robot
                if robot.name == "unitree_g1":
                    phase = "robot.reset"
                    robot.reset()

                phase = "reset record_loop"
                record_loop(
                    robot=robot,
                    events=events,
                    fps=fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    control_time_s=reset_time_s,
                    single_task=single_task,
                    display_data=display_data,
                )

            if events["rerecord_episode"]:
                log_say("Re-record episode", play_sounds)
                events["rerecord_episode"] = False
                events["exit_early"] = False
                terminal = True
                if lifecycle is not None:
                    lifecycle.on_episode_rerecord(
                        robot=robot, dataset=dataset, episode_index=recorded_episodes
                    )
                dataset.clear_episode_buffer()
                continue

            if events["stop_recording"] and lifecycle is not None:
                # An explicitly stopped episode is incomplete and must never be
                # saved as if it had been completed.
                terminal = True
                lifecycle.on_episode_incomplete(
                    robot=robot,
                    dataset=dataset,
                    episode_index=recorded_episodes,
                    reason="operator stop before save",
                )
            else:
                terminal = True
                if lifecycle is not None:
                    lifecycle.save_episode(
                        robot=robot, dataset=dataset, episode_index=recorded_episodes
                    )
                else:
                    dataset.save_episode()
                recorded_episodes += 1
        except BaseException as error:
            if lifecycle is not None and not terminal:
                bound_error = error
                bound_reason = f"{phase} raised {type(bound_error).__name__}: {bound_error}"
                bound_index = recorded_episodes
                _notify_lifecycle_observer(
                    "on_episode_incomplete",
                    partial(
                        lifecycle.on_episode_incomplete,
                        robot=robot,
                        dataset=dataset,
                        episode_index=bound_index,
                        reason=bound_reason,
                    ),
                    original_error=bound_error,
                )
            raise
    return recorded_episodes


def finalize_recorded_dataset(
    dataset: LeRobotDataset,
    *,
    lifecycle: RecordEpisodeLifecycleObserver | None = None,
    recorded_episode_count: int = 0,
) -> None:
    """Finalize the dataset through its public lifecycle, notifying the observer.

    With ``lifecycle=None`` this is exactly ``dataset.finalize()``: any
    exception propagates unchanged and there is no extra behavior. With an
    observer, a finalize failure is reported through
    ``on_dataset_finalize_failure`` (whose own exceptions are logged and never
    mask the finalize error) and the original exception keeps propagating; a
    finalize success is reported through ``on_dataset_finalize_success``,
    whose exception propagates unless another exception is already in flight
    (in that case it is only logged, never masking the original error).
    """

    if lifecycle is None:
        dataset.finalize()
        return
    try:
        dataset.finalize()
    except BaseException as finalize_error:
        bound_error = finalize_error
        _notify_lifecycle_observer(
            "on_dataset_finalize_failure",
            partial(
                lifecycle.on_dataset_finalize_failure, dataset=dataset, error=bound_error
            ),
            original_error=bound_error,
        )
        raise
    bound_count = recorded_episode_count
    _notify_lifecycle_observer(
        "on_dataset_finalize_success",
        partial(
            lifecycle.on_dataset_finalize_success,
            dataset=dataset,
            recorded_episode_count=bound_count,
        ),
        original_error=sys.exc_info()[1],
    )


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    log_dir = Path("log")
    log_dir.mkdir(exist_ok=True)
    timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_file_path = log_dir / f"record_{timestamp_str}.log"
    init_logging(log_file=str(log_file_path))
    logging.getLogger().setLevel(logging.INFO)
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_type = cfg.teleop.type if cfg.teleop is not None else None
    robot_type = cfg.robot.type if cfg.robot else None
    teleop_action_processor, robot_action_processor, robot_observation_processor = make_processors_for_teleop_robot_pair(
        teleop_type=teleop_type,
        robot_type=robot_type,
    )

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None
    recorded_episodes = 0
    # The generic record entrypoint never activates a lifecycle observer: the
    # hook is optional and exists so explicitly-injected coordinators (tested
    # offline) can orchestrate episode saves without changing default behavior.
    lifecycle = None

    try:
        if cfg.resume:
            dataset = LeRobotDataset(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

            if hasattr(robot, "cameras") and len(robot.cameras) > 0:
                dataset.start_image_writer(
                    num_processes=cfg.dataset.num_image_writer_processes,
                    num_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )

        robot.connect()
        if teleop is not None:
            teleop.connect()

        listener, events = init_keyboard_listener()

        if not cfg.dataset.streaming_encoding:
            logging.info(
                "Streaming encoding is disabled. If you have capable hardware, consider enabling it for way faster episode saving. --dataset.streaming_encoding=true --dataset.encoder_threads=2 # --dataset.vcodec=auto. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding"
            )

        with VideoEncodingManager(dataset):
            recorded_episodes = record_episode_sessions(
                robot=robot,
                teleop=teleop,
                policy=policy,
                preprocessor=preprocessor,
                postprocessor=postprocessor,
                teleop_action_processor=teleop_action_processor,
                robot_action_processor=robot_action_processor,
                robot_observation_processor=robot_observation_processor,
                dataset=dataset,
                events=events,
                fps=cfg.dataset.fps,
                num_episodes=cfg.dataset.num_episodes,
                episode_time_s=cfg.dataset.episode_time_s,
                reset_time_s=cfg.dataset.reset_time_s,
                single_task=cfg.dataset.single_task,
                play_sounds=cfg.play_sounds,
                display_data=cfg.display_data,
                display_compressed_images=display_compressed_images,
                lifecycle=lifecycle,
            )
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            finalize_recorded_dataset(
                dataset, lifecycle=lifecycle, recorded_episode_count=recorded_episodes
            )

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
