#!/usr/bin/env python

# Copyright 2026 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Contracts for the AUBO depth-enhanced VLA bamboo-sorting research."""

from .authorization_contract import (
    CONTROL_SOURCES,
    EXECUTION_AUTHORIZATION_SCHEMA_VERSION,
    ExecutionAuthorizationV1,
    build_authorization_manifest,
)
from .c0_capture_contract import (
    C0_BATCH_MANIFEST_SCHEMA_VERSION,
    C0_CAPTURE_PROFILE_ID,
    C0_DATASET_FPS,
    C0_EPISODE_MANIFEST_SCHEMA_VERSION,
    C0_EXPECTED_EPISODE_COUNT,
    C0_HUMAN_OUTCOMES,
    C0_INSTRUCTION_ID,
    C0_SENSOR_STREAMS,
    C0_SENSOR_TIMESTAMP_SCHEMA_VERSION,
    C0_SPLIT_NAMES,
    C0_SPLIT_RULE_VERSION,
    C0_SYNC_METHODS,
    GRIPPER_STATE_SEMANTICS,
    C0BatchManifestV1,
    C0EpisodeManifestV1,
    C0SensorTimestampV1,
)
from .c0_gripper_auditor import (
    C0_GRIPPER_AUDIT_REPORT_SCHEMA_VERSION,
    C0GripperAuditReportV1,
    audit_gripper_episode,
)
from .c0_gripper_contract import (
    C0_GRIPPER_EPISODE_BINDING_SCHEMA_VERSION,
    C0_GRIPPER_EPISODE_TRACE_SCHEMA_VERSION,
    C0_GRIPPER_EVENT_SCHEMA_VERSION,
    C0_GRIPPER_EVENT_TYPES,
    C0GripperEpisodeBindingV1,
    C0GripperEpisodeTraceV1,
    C0GripperEventV1,
    derive_gripper_transition_frames,
)
from .c0_gripper_controller_binding import (
    C0_GRIPPER_CONTROLLER_BINDING_REPORT_SCHEMA_VERSION,
    C0GripperControllerBindingReportV1,
    audit_c0_gripper_controller_binding,
)
from .c0_gripper_controller_sidecar import (
    C0_GRIPPER_CONTROLLER_ATTEMPT_SCHEMA_VERSION,
    C0_GRIPPER_CONTROLLER_SIDECAR_SCHEMA_VERSION,
    C0GripperControllerAttemptV1,
    C0GripperControllerSidecarV1,
    build_c0_gripper_event_from_aubo_trace,
)
from .c0_gripper_dataset_auditor import (
    C0_GRIPPER_DATASET_AUDIT_REPORT_SCHEMA_VERSION,
    C0_GRIPPER_SLICE_DIGEST_SCHEMA_VERSION,
    C0GripperDatasetAuditReportV1,
    C0GripperDatasetSliceDigestV1,
    audit_c0_gripper_dataset_episode,
)
from .capture_manifest import (
    CAPTURE_PURPOSES,
    RAW_CAPTURE_MANIFEST_SCHEMA_VERSION,
    RawArtifactRecord,
    RawCaptureManifestV1,
    reserve_capture_directory,
)
from .contracts import (
    ACTION_CONTROL_MODE,
    ACTION_FIELD_NAMES,
    ACTION_FIELD_SPECS,
    ACTION_SCHEMA_VERSION,
    CONTROL_FIXED_ID,
    INSTRUCTION_LANGUAGE,
    INSTRUCTION_SCHEMA_VERSION,
    INSTRUCTION_SPECS,
    ActionFieldSpec,
    InstructionSpec,
    build_action_manifest,
    build_instruction_manifest,
    validate_action_vector,
    validate_instruction_fields,
)
from .depth_gate import (
    DEPTH_GATE_SCHEMA_VERSION,
    STATIC_GROUP_MINIMUMS,
    DepthGateDecision,
    DepthGateEvidence,
    DepthGateMetrics,
    DepthGateResult,
    build_depth_gate_manifest,
    evaluate_depth_gate,
)
from .depth_gate_analysis import (
    DEPTH_GATE_ANALYSIS_SCHEMA_VERSION,
    DepthGateAnalysisReport,
    MotionSequenceMeasurements,
    StaticPoseMeasurements,
    analyze_depth_gate,
)
from .lerobot_bridge import (
    CAMERASET_V1_LEROBOT_BRIDGE_VERSION,
    CAMERASET_V2_LEROBOT_BRIDGE_VERSION,
    CURRENT_CAMERASET_LEROBOT_BRIDGE_VERSION,
    FORBIDDEN_VLA_KEYS,
    build_camera_set_v2_lerobot_features,
    build_cameras_set_v1_lerobot_features,
    observation_to_lerobot_frame,
    sha256_file,
    write_scene_manifest,
)
from .observation_contract import (
    BASE_TIMESTAMP_STREAMS,
    DEPTH_STREAM_KEY,
    OBSERVATION_SCHEMA_VERSION,
    OBSERVATION_STATE_FIELD_NAMES,
    OBSERVATION_STATE_FIELD_SPECS,
    RGB_STREAM_KEYS,
    CameraIntrinsics,
    EmbodiedObservationV1,
    ObservationStateFieldSpec,
    SensorTimestamp,
    TemporalAlignmentMetrics,
    build_observation_manifest,
    validate_temporal_alignment,
)
from .offline_vla_runtime import PHASE_B_POLICY_ID, OfflineVLARuntime
from .policy_prediction import (
    POLICY_PREDICTION_SCHEMA_VERSION,
    PolicyPredictionV1,
)
from .rl_contract import (
    MODE_REQUIRED_GATES,
    REWARD_SCHEMA_VERSION,
    REWARD_SOURCES,
    RL_OBSERVATION_REF_SCHEMA_VERSION,
    RL_READINESS_MODES,
    RL_READINESS_SCHEMA_VERSION,
    RL_TRANSITION_SCHEMA_VERSION,
    TRANSITION_CONTROL_SOURCES,
    RewardSchemaV1,
    RLObservationRefV1,
    RLReadinessReportV1,
    RLTransitionV1,
)
from .rl_episode_contract import (
    EPISODE_TERMINATION_REASONS,
    REPLAY_SPLIT_NAMES,
    RESET_REASONS,
    RESET_RECORD_SCHEMA_VERSION,
    RL_EPISODE_MANIFEST_SCHEMA_VERSION,
    RL_REPLAY_MANIFEST_SCHEMA_VERSION,
    ResetRecordV1,
    RLEpisodeManifestV1,
    RLReplayManifestV1,
)
from .smolvla_adapter import (
    DEFAULT_IMAGE_HEIGHT,
    DEFAULT_IMAGE_WIDTH,
    SmolVLAOfflineForwardAdapter,
    prepare_smolvla_inference_frame,
    validate_smolvla_policy_contract,
)
from .thin_safety_gate import (
    THIN_SAFETY_GATE_SCHEMA_VERSION,
    GatedActionChunk,
    ThinSafetyGate,
    ThinSafetyGateLimits,
)

__all__ = [
    "CONTROL_SOURCES",
    "EXECUTION_AUTHORIZATION_SCHEMA_VERSION",
    "ExecutionAuthorizationV1",
    "build_authorization_manifest",
    "CAPTURE_PURPOSES",
    "RAW_CAPTURE_MANIFEST_SCHEMA_VERSION",
    "RawArtifactRecord",
    "RawCaptureManifestV1",
    "reserve_capture_directory",
    "C0_BATCH_MANIFEST_SCHEMA_VERSION",
    "C0_CAPTURE_PROFILE_ID",
    "C0_DATASET_FPS",
    "C0_EPISODE_MANIFEST_SCHEMA_VERSION",
    "C0_EXPECTED_EPISODE_COUNT",
    "C0_HUMAN_OUTCOMES",
    "C0_INSTRUCTION_ID",
    "C0_SENSOR_STREAMS",
    "C0_SENSOR_TIMESTAMP_SCHEMA_VERSION",
    "C0_SPLIT_NAMES",
    "C0_SPLIT_RULE_VERSION",
    "C0_SYNC_METHODS",
    "GRIPPER_STATE_SEMANTICS",
    "C0BatchManifestV1",
    "C0EpisodeManifestV1",
    "C0SensorTimestampV1",
    "C0_GRIPPER_AUDIT_REPORT_SCHEMA_VERSION",
    "C0_GRIPPER_CONTROLLER_ATTEMPT_SCHEMA_VERSION",
    "C0_GRIPPER_CONTROLLER_BINDING_REPORT_SCHEMA_VERSION",
    "C0_GRIPPER_CONTROLLER_SIDECAR_SCHEMA_VERSION",
    "C0_GRIPPER_DATASET_AUDIT_REPORT_SCHEMA_VERSION",
    "C0_GRIPPER_EPISODE_BINDING_SCHEMA_VERSION",
    "C0_GRIPPER_EPISODE_TRACE_SCHEMA_VERSION",
    "C0_GRIPPER_EVENT_SCHEMA_VERSION",
    "C0_GRIPPER_EVENT_TYPES",
    "C0_GRIPPER_SLICE_DIGEST_SCHEMA_VERSION",
    "C0GripperAuditReportV1",
    "C0GripperControllerAttemptV1",
    "C0GripperControllerBindingReportV1",
    "C0GripperControllerSidecarV1",
    "C0GripperDatasetAuditReportV1",
    "C0GripperDatasetSliceDigestV1",
    "C0GripperEpisodeBindingV1",
    "C0GripperEpisodeTraceV1",
    "C0GripperEventV1",
    "audit_c0_gripper_dataset_episode",
    "audit_c0_gripper_controller_binding",
    "audit_gripper_episode",
    "build_c0_gripper_event_from_aubo_trace",
    "derive_gripper_transition_frames",
    "ACTION_CONTROL_MODE",
    "ACTION_FIELD_NAMES",
    "ACTION_FIELD_SPECS",
    "ACTION_SCHEMA_VERSION",
    "CONTROL_FIXED_ID",
    "INSTRUCTION_LANGUAGE",
    "INSTRUCTION_SCHEMA_VERSION",
    "INSTRUCTION_SPECS",
    "ActionFieldSpec",
    "InstructionSpec",
    "build_action_manifest",
    "build_instruction_manifest",
    "validate_action_vector",
    "validate_instruction_fields",
    "DEPTH_GATE_SCHEMA_VERSION",
    "STATIC_GROUP_MINIMUMS",
    "DepthGateDecision",
    "DepthGateEvidence",
    "DepthGateMetrics",
    "DepthGateResult",
    "build_depth_gate_manifest",
    "evaluate_depth_gate",
    "DEPTH_GATE_ANALYSIS_SCHEMA_VERSION",
    "DepthGateAnalysisReport",
    "MotionSequenceMeasurements",
    "StaticPoseMeasurements",
    "analyze_depth_gate",
    "CAMERASET_V1_LEROBOT_BRIDGE_VERSION",
    "CAMERASET_V2_LEROBOT_BRIDGE_VERSION",
    "CURRENT_CAMERASET_LEROBOT_BRIDGE_VERSION",
    "FORBIDDEN_VLA_KEYS",
    "build_camera_set_v2_lerobot_features",
    "build_cameras_set_v1_lerobot_features",
    "observation_to_lerobot_frame",
    "sha256_file",
    "write_scene_manifest",
    "BASE_TIMESTAMP_STREAMS",
    "DEPTH_STREAM_KEY",
    "OBSERVATION_SCHEMA_VERSION",
    "OBSERVATION_STATE_FIELD_NAMES",
    "OBSERVATION_STATE_FIELD_SPECS",
    "RGB_STREAM_KEYS",
    "CameraIntrinsics",
    "EmbodiedObservationV1",
    "ObservationStateFieldSpec",
    "SensorTimestamp",
    "TemporalAlignmentMetrics",
    "build_observation_manifest",
    "validate_temporal_alignment",
    "PHASE_B_POLICY_ID",
    "OfflineVLARuntime",
    "POLICY_PREDICTION_SCHEMA_VERSION",
    "PolicyPredictionV1",
    "MODE_REQUIRED_GATES",
    "REWARD_SCHEMA_VERSION",
    "REWARD_SOURCES",
    "RL_OBSERVATION_REF_SCHEMA_VERSION",
    "RL_READINESS_MODES",
    "RL_READINESS_SCHEMA_VERSION",
    "RL_TRANSITION_SCHEMA_VERSION",
    "TRANSITION_CONTROL_SOURCES",
    "RLObservationRefV1",
    "RLReadinessReportV1",
    "RLTransitionV1",
    "RewardSchemaV1",
    "EPISODE_TERMINATION_REASONS",
    "REPLAY_SPLIT_NAMES",
    "RESET_REASONS",
    "RESET_RECORD_SCHEMA_VERSION",
    "RL_EPISODE_MANIFEST_SCHEMA_VERSION",
    "RL_REPLAY_MANIFEST_SCHEMA_VERSION",
    "RLEpisodeManifestV1",
    "RLReplayManifestV1",
    "ResetRecordV1",
    "DEFAULT_IMAGE_HEIGHT",
    "DEFAULT_IMAGE_WIDTH",
    "SmolVLAOfflineForwardAdapter",
    "prepare_smolvla_inference_frame",
    "validate_smolvla_policy_contract",
    "THIN_SAFETY_GATE_SCHEMA_VERSION",
    "GatedActionChunk",
    "ThinSafetyGate",
    "ThinSafetyGateLimits",
]
